import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchBox from '../components/SearchBox'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{fontSize: "5rem"}}>🌦🕵🏻‍♂️</div>
        <h1 className={styles.title}>
          Welcome to Weather Inspector
        </h1>

        <div className="container">
          <SearchBox />
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          
          <span className={styles.logo}>
          Powered by - OpenWeatherMap & GLJMedia
          </span>
        </a>
      </footer>
    </div>
  )
}
